# default theme is jekyll-theme-primer (https://github.com/pages-themes/primer)
theme: minima
title: Individual Software Process
#description Course Material for ISP
url: "https://cpske.github.io/ISP/"
include: [code-quality, code-review]
# if exclude 'code' then code-* is also excluded
exclude: [bin, ISP, quiz, solution, misc, old, Gemfile, Gemfile.lock, Jittat, Paruj]
# github username shown in Minima theme
github_username: cpske
# Use Git's markdown syntax
markdown: kramdown
# DON"T USE "permalink: pretty" it adds "/" after URLs of pages 


# Default layout for pages, so you don't need to set "layout: page" in each
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# 10/20/2020 I hardcoded this into google_analytics.html
plugins:
  - jekyll-seo-tag
google_analytics: "UA-104768257-3"
